services:
  - type: web
    name: snos-tool-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://user:pass@host:port/dbname  # Опционально для PostgreSQL
    autoDeploy: true
    healthCheckPath: /