services:
  - type: web
    name: snos-license-server
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app  # или gunicorn wsgi:app если создали wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
